### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by san222631**
增加了3個api以及用來抓JSON的python

### CODE REVIEW

**Comment by san222631** [comment]
增加了3個api以及用來抓JSON的python

**Review by cwpeng — CHANGES_REQUESTED** [review]
Where are your testing URLs?

**Comment by san222631** [comment]
李庭均
http://13.53.168.98:8000/api/attractions/?page=1
http://13.53.168.98:8000/api/attractions/?page=0&keyword=劍潭
http://13.53.168.98:8000/api/attractions/?page=0&keyword=北
http://13.53.168.98:8000/api/attraction/10
http://13.53.168.98:8000/api/mrts

**Review by cwpeng — CHANGES_REQUESTED** [review]
MRT names should not contain duplicate names, and should be order by number of around attractions.

**Comment by san222631** [comment]
修改了/api/mrts，所有捷運站只出現一次，排除null因為不是捷運站，照著捷運站周邊景點數量排順序，由多排到少

**Comment by san222631** [comment]
修正了/api/mrts，所有捷運站只出現一次，排除null因為不是捷運站，照著周邊景點的數量排列，從多到少排列
http://13.53.168.98:8000/api/mrts

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
