### PR TITLE
Part4-1st commit

### PR DESCRIPTION
**Pull request by san222631**
李庭均
http://13.53.168.98:8000/
http://13.53.168.98:8000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Response format of User APIs should align with API specs.

**Comment by san222631** [comment]
1. response changed - signin/signup
李庭均
http://13.53.168.98:8000/
http://13.53.168.98:8000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
Response format of **User APIs** should align with **API specs**.

**Comment by san222631** [comment]
1. 更改了登入時，送response的api (本來自以為是從PUT api直接再度轉送GET api)
2. response的格式有更改
李庭均
http://13.53.168.98:8000/
http://13.53.168.98:8000/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
