### PR TITLE
Part5-1st commit

### PR DESCRIPTION
**Pull request by san222631**
李庭均
http://13.53.168.98:8000/
http://13.53.168.98:8000/attraction/10
http://13.53.168.98:8000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout width of your booking page exceeds the screen width in small to middle size of devices.

**Comment by san222631** [comment]
Changed the booking layout from small to medium screen size
李庭均
http://13.53.168.98:8000/
http://13.53.168.98:8000/attraction/10
http://13.53.168.98:8000/booking

**Review by cwpeng — APPROVED** [review]
OK. Done.

You have to resovle conflicts and merge pull request to main branch.

**Comment by san222631** [comment]
Got it! Will figure it out!

**Pull request merged**
