### PR TITLE
Part3 - 1st commit

### PR DESCRIPTION
**Pull request by san222631**
李庭均
http://13.53.168.98:8000/
http://13.53.168.98:8000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- There is no space between navigation bar and image in mobile layout.
- Take attention on the color of data input element.
13 53 168 98_8000_attraction_10

**Comment by san222631** [comment]
CSS changed for 
1. space between navigation & image in mobile mode.
2. color and size of radio button

李庭均
http://13.53.168.98:8000/
http://13.53.168.98:8000/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by cwpeng** [comment]
You have to resolve conflicts and merge this pull request after review approval.

**Pull request merged**
